# Generated by Django 5.0.1 on 2024-04-16 14:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_rename_specialist_profession_and_more"),
        ("projects", "0003_alter_direction_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectspecialist",
            name="projects_projectspecialist_unique_specialist_per_project",
        ),
        migrations.RemoveField(
            model_name="projectspecialist",
            name="specialist",
        ),
        migrations.AddField(
            model_name="projectspecialist",
            name="profession",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.profession",
                verbose_name="профессия",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                max_length=750,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=50,
                        message="Длина поля от 50 до 750 символов.",
                    )
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectspecialist",
            constraint=models.UniqueConstraint(
                fields=("project", "profession", "level"),
                name="projects_projectspecialist_unique_specialist_per_project",
            ),
        ),
    ]
