# Generated by Django 5.0.1 on 2024-04-24 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0004_remove_projectspecialist_projects_projectspecialist_unique_specialist_per_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон может содержать: цифры, спецсимволы, длина не должна превышать 12 символов",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
