# Generated by Django 5.0.1 on 2024-04-25 14:31

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0004_remove_projectspecialist_projects_projectspecialist_unique_specialist_per_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                max_length=750,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=50,
                        message="Длина поля от 50 до 750 символов.",
                    ),
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Описание может содержать: кириллические и латинские буквы, цифры и специальные символы.",
                        regex="(^[\\Wa-zа-яё0-9\\s]+)\\Z",
                    ),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="directions",
            field=models.ManyToManyField(
                related_name="projects_direction",
                to="projects.direction",
                verbose_name="Направления разработки",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="email",
            field=models.EmailField(
                blank=True, max_length=256, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(
                blank=True,
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Длина поля от 5 до 256 символов.",
                    )
                ],
                verbose_name="Ссылка",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="phone_number",
            field=models.TextField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон может содержать: цифры, спецсимволы, длина не должна превышать 12 символов",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="telegram_nick",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Длина поля от 5 до 32 символов.",
                    ),
                    django.core.validators.RegexValidator(
                        message="Введите корректное имя пользователя. Оно может состоять из латинских букв, цифр и символа подчеркивания.",
                        regex="^[a-zA-Z0-9_]+$",
                    ),
                ],
                verbose_name="Ник в телеграм",
            ),
        ),
    ]
