# Generated by Django 5.0.1 on 2024-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0005_alter_project_description_alter_project_directions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectspecialist",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "junior"),
                    (2, "middle"),
                    (3, "senior"),
                    (4, "lead"),
                ],
                verbose_name="Уровень",
            ),
        ),
    ]
