# Generated by Django 5.0.1 on 2024-05-12 18:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_projectspecialist_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                null=True, verbose_name="Поле полнотекствого поиска"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="projects_pr_search__1d35f9_gin"
            ),
        ),
    ]
