# Generated by Django 5.0.1 on 2024-05-15 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_project_search_vector_and_more"),
        (
            "projects",
            "0009_alter_project_busyness_alter_project_ended_and_more",
        ),
    ]

    operations = []
