# Generated by Django 5.0.1 on 2024-06-23 08:18

import apps.general.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_project_email_alter_project_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=apps.general.fields.CustomURLField(
                blank=True,
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Длина поля от 5 до 256 символов.",
                    )
                ],
                verbose_name="Ссылка",
            ),
        ),
    ]
