# Generated by Django 5.0 on 2024-07-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_rename_specialist_profession_and_more"),
        ("projects", "0011_alter_project_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.profession",
                        verbose_name="Профессия",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        to="general.skill", verbose_name="Навыки"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник проекта",
                "verbose_name_plural": "Участники проекта",
                "default_related_name": "project_participants",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="participants_new",
            field=models.ManyToManyField(
                related_name="projects_participated_new",
                through="projects.ProjectParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectparticipant",
            constraint=models.UniqueConstraint(
                fields=("project", "user", "profession"),
                name="projects_projectparticipant_unique_participant_role_per_project",
            ),
        ),
    ]
