# Generated by Django 5.0 on 2024-07-06 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_migrate_participants_to_new_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="participants",
        ),
    ]
