# Generated by Django 5.0 on 2024-07-06 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_remove_project_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="participants_new",
            new_name="participants",
        ),
    ]
