# Generated by Django 5.0.1 on 2024-10-17 19:16

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_alter_invitationtoproject_answer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "description"],
                name="project_search_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
