# Generated by Django 5.0.1 on 2024-10-28 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_project_project_search_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invitationtoproject",
            name="projects_invitationtoproject_unique_request_per_project",
        ),
        migrations.RemoveConstraint(
            model_name="participationrequest",
            name="projects_participationrequest_unique_request_per_project",
        ),
        migrations.RemoveField(
            model_name="invitationtoproject",
            name="status",
        ),
        migrations.RemoveField(
            model_name="participationrequest",
            name="status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AddField(
            model_name="invitationtoproject",
            name="request_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "В процессе"), (2, "Принята"), (3, "Отклонена")],
                default=1,
                verbose_name="Статус запроса на участие или приглашения",
            ),
        ),
        migrations.AddField(
            model_name="participationrequest",
            name="request_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "В процессе"), (2, "Принята"), (3, "Отклонена")],
                default=1,
                verbose_name="Статус запроса на участие или приглашения",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Черновик"), (2, "Активен"), (3, "Завершен")],
                default=2,
                verbose_name="Статус проекта",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="invitationtoproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("request_status", 1)),
                fields=("user", "position"),
                name="projects_invitationtoproject_unique_request_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="participationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("request_status", 1)),
                fields=("project", "user", "position"),
                name="projects_participationrequest_unique_request_per_project",
            ),
        ),
    ]
