# Generated by Django 5.0.1 on 2024-05-17 16:39

import apps.general.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=apps.general.fields.CustomEmailField(
                max_length=256, unique=True, verbose_name="Email address"
            ),
        ),
    ]
