MAX_LENGTH_NAME = 30
MAX_LENGTH_COUNTRY = 255
MAX_LENGTH_CITY = 255
MAX_LENGTH_ABOUT = 750
MAX_LENGTH_URL = 256
MIN_LENGTH_NAME = 2
MIN_LENGTH_ABOUT = 50
MIN_LENGTH_PORTFOLIO = 5
REGEX_PROFILE_NAME = r"^[a-zA-Zа-яА-Я -]+$"
REGEX_PROFILE_ABOUT = r"^[a-zA-Zа-яА-Я0-9\s!@#$%^&*()-_+=<>?]+$"
MAX_PROFILE_PROFESSIONS = 2
