# Generated by Django 5.0.1 on 2024-04-25 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=256, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.TextField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон может содержать: цифры, спецсимволы, длина не должна превышать 12 символов",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telegram_nick",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Длина поля от 5 до 32 символов.",
                    ),
                    django.core.validators.RegexValidator(
                        message="Введите корректное имя пользователя. Оно может состоять из латинских букв, цифр и символа подчеркивания.",
                        regex="^[a-zA-Z0-9_]+$",
                    ),
                ],
                verbose_name="Ник в телеграм",
            ),
        ),
    ]
