# Generated by Django 5.0.1 on 2024-04-24 14:41

import apps.profile.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_rename_specialist_profession_and_more"),
        ("profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userskill",
            name="profile_userskill_unique_skill_per_user"
        ),
        migrations.RemoveConstraint(
            model_name="userspecialization",
            name="profile_userspecialization_unique_specialization_per_user"
        ),
        migrations.RemoveField(
            model_name="userspecialization",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="userspecialization",
            name="specialization",
        ),
        migrations.RemoveField(
            model_name="userspecialization",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="level",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[apps.profile.validators.validate_image],
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[apps.profile.validators.BirthdayValidator],
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон может содержать: цифры, спецсимволы, длина не должна превышать 12 символов",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="portfolio_link",
            field=models.URLField(
                blank=True,
                max_length=256,
                validators=[
                    django.core.validators.URLValidator(
                        message="Введите корректный URL"
                    ),
                    django.core.validators.MinLengthValidator(limit_value=5),
                ],
                verbose_name="Ссылка на портфолио",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ready_to_participate",
            field=models.BooleanField(
                default=False, verbose_name="Готов(а) к участию в проектах"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "intern"),
                            (2, "junior"),
                            (3, "middle"),
                            (4, "senior"),
                            (5, "lead"),
                        ],
                        null=True,
                        verbose_name="Уровень квалификации",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.profession",
                        verbose_name="Профессия",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        to="general.skill", verbose_name="Навыки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="professions",
            field=models.ManyToManyField(
                through="profile.Specialist",
                to="general.profession",
                verbose_name="Профессии",
            ),
        ),
        migrations.DeleteModel(
            name="UserSkill",
        ),
        migrations.DeleteModel(
            name="UserSpecialization",
        ),
        migrations.AddConstraint(
            model_name="specialist",
            constraint=models.UniqueConstraint(
                fields=("profile", "profession"),
                name="profile_specialist_unique_profession_per_profile",
            ),
        ),
    ]
