# Generated by Django 5.0.1 on 2024-04-24 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_remove_userspecialization_profile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={
                "default_related_name": "profile_professions",
                "verbose_name": "Специалист",
            },
        ),
    ]
