# Generated by Django 5.0.1 on 2024-04-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_alter_specialist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={
                "default_related_name": "profile_professions",
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
        migrations.AlterField(
            model_name="specialist",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profile.profile",
                verbose_name="Профиль пользователя",
            ),
        ),
    ]
