# Generated by Django 5.0.1 on 2024-05-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_remove_userspecialization_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="visible_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "All"), (2, "Only creator"), (3, "Nobody")],
                default=3,
                verbose_name="Видимость",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="visible_status_contacts",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "All"), (2, "Only creator"), (3, "Nobody")],
                default=3,
                verbose_name="Видимость контактов",
            ),
        ),
    ]
