# Generated by Django 5.0.1 on 2024-06-19 09:03

import apps.general.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_alter_profile_email_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="portfolio_link",
            field=models.URLField(
                blank=True,
                max_length=256,
                validators=[
                    apps.general.validators.CustomURLValidator(),
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Длинна URL-адреса должна быть от 5 до 256 символов.",
                    ),
                ],
                verbose_name="Ссылка на портфолио",
            ),
        ),
    ]
