# Generated by Django 5.0.1 on 2025-01-06 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0010_add_trigramextension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(
                blank=True,
                max_length=1500,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите кириллицу или латиницу",
                        regex="^[\\wа-яА-ЯёЁ0-9\\s<>,.?!'\\\"/\\-+:;@#\\$%\\^&\\*\\(\\)\\[\\]\\{\\}]*$|^<.*>$",
                    ),
                    django.core.validators.MinLengthValidator(limit_value=20),
                ],
                verbose_name="О себе",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите кириллицу или латиницу",
                        regex="^[a-zA-Zа-яА-ЯёЁ-]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=2, message="Должно быть минимум символов"
                    ),
                ],
                verbose_name="Имя",
            ),
        ),
    ]
