# Generated by Django 5.0.1 on 2024-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_alter_specialist_specialization_and_more"),
        ("profile", "0001_initial"),
        ("projects", "0003_alter_direction_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Specialist",
            new_name="Profession",
        ),
        migrations.AlterModelOptions(
            name="profession",
            options={
                "verbose_name": "Профессия",
                "verbose_name_plural": "Профессии",
            },
        ),
        migrations.RemoveConstraint(
            model_name="profession",
            name="general_specialist_unique_specialist",
        ),
        migrations.AddConstraint(
            model_name="profession",
            constraint=models.UniqueConstraint(
                fields=("specialty", "specialization"),
                name="general_profession_unique_profession",
            ),
        ),
    ]
