name: Codepet build nginx and backend from develop

on:
  push:
    branches: [ 'develop' ]
  workflow_dispatch:

jobs:
  build_and_push_to_docker_hub_backend:
    name: Push backend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}_backend:latest

  build_and_push_to_docker_hub_nginx:
    name: Push nginx Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./infra/nginx/
          push: true
          build-args: |
            NGINX_NAME=${{ secrets.NGINX_DEV}}
            SERVER_NAME=${{ secrets.SERVER_NAME_DEV }}
            SERVER_HOST=${{ secrets.SERVER_HOST_DEV }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}_nginx:latest

  deploy_uses_other_file_from_QA:
    if:
      contains('
        refs/heads/develop
      ', github.ref)
    uses: Pet-projects-CodePET/Backend/.github/workflows/deploy.yml@develop
    needs:
      - build_and_push_to_docker_hub_backend
      - build_and_push_to_docker_hub_nginx
    secrets: inherit
